### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by streambinder** [ryanluker/vscode-coverage-gutters#210]
**Describe the bug**
Cannot parse `jacoco.xml` report:
```
[1552581399921][coverageservice]: INITIALIZING
[1552581539653][coverageservice]: LOADING
[1552581540818][coverageservice]: Loading 1 file(s)
[1552581540828][coverageservice]: Loaded 1 data file(s)
[1552581540944][coverageparser][jacoco-parse]: Error: filename: main/target/site/jacoco/jacoco.xml Cannot read property 'filter' of undefined
[1552581540944][coverageparser][jacoco-parse]: Stacktrace: TypeError: filename: main/target/site/jacoco/jacoco.xml Cannot read property 'filter' of undefined
	at getCounter (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:9:27)
	at /home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:33:27
	at Array.map (<anonymous>)
	at /home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:23:35
	at Array.forEach (<anonymous>)
	at unpackage (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:21:14)
	at /home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:123:22
	at Parser.<anonymous> (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:303:18)
	at Parser.emit (events.js:182:13)
	at SAXParser.onclosetag (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:261:26)
	at emit (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:624:35)
	at emitNode (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:629:5)
	at closeTag (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:889:7)
	at SAXParser.write (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:1436:13)
	at Parser.exports.Parser.Parser.parseString (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:322:31)
	at Parser.bind [as parseString] (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:5:59)
	at exports.parseString (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:354:19)
	at Object.parse.parseContent (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:116:5)
	at xmlExtractJacoco.Promise (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:103:32)
	at new module.exports.e.exports (/home/streambinder/.vscode/extensions/vscjava.vscode-java-pack-0.6.0/out/extension.js:1:73069)
	at CoverageParser.xmlExtractJacoco (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:94:16)
	at CoverageParser.<anonymous> (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:42:47)
	at Generator.next (<anonymous>)
	at __awaiter (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:7:71)
	at new module.exports.e.exports (/home/streambinder/.vscode/extensions/vscjava.vscode-java-pack-0.6.0/out/extension.js:1:73069)
	at __awaiter (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:3:12)
	at CoverageParser.filesToSections (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:27:16)
	at CoverageService.<anonymous> (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/coverage-system/coverageservice.js:76:64)
	at Generator.next (<anonymous>)
	at fulfilled (/home/streambinder/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/coverage-system/coverageservice.js:4:58)
	at o (/home/streambinder/.vscode/extensions/vscjava.vscode-java-pack-0.6.0/out/extension.js:1:69130)
	at /home/streambinder/.vscode/extensions/vscjava.vscode-java-pack-0.6.0/out/extension.js:1:69474
[1552581540947][coverageservice]: Caching 0 coverage(s)
[1552581540947][printDataCoverage]: Coverage ->
[1552581540947][coverageservice]: READY
[1552581540947][coverageservice]: RENDERING
[1552581540947][coverageservice]: READY
[1552581542384][coverageservice]: RENDERING
[1552581542384][coverageservice]: READY
[1552581542416][coverageservice]: RENDERING
[1552581542418][coverageservice]: READY
```

**To Reproduce**
I actually just trigger coverage a `Display Coverage` command.

**Expected behaviour**
A correctly rendered coverage report.
Let me know if you need the XML report (I eventually need to clean it up from some business details).

**Desktop (please complete the following information):**
 - OS: Linux
 - Extension Version 2.3.1
 - VSCode Version 1.32.1

**Additional context**
None.

**Comment by streambinder** [comment]
This seems to get fixed updating `jacoco-parse` to `2.0.1`.

**Comment by ryanluker** [comment]
@streambinder thanks for submitting a ticket! I have incremented the version on that dependency and all the java integration tests still pass, so we look good to go :+1: https://github.com/ryanluker/vscode-coverage-gutters/pull/211. I am not planning on releasing 2.4.0 for a while so I have included the vsix installer below that you can use in the meantime.
[vscode-coverage-gutters-2.4.0.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/2975396/vscode-coverage-gutters-2.4.0.zip)

**Comment by Serotonin7** [comment]
The above fixed my issue! Found the following useful...
[How to install from vsix in Visual Studio Code]( https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)
