### ISSUE TITLE
Exception in parsing jacoco xml report

### ISSUE THREAD

**Issue by foxpluto** [ryanluker/vscode-coverage-gutters#217]
**Describe the bug**
Exception thrown "Cannot read property 'filter' of undefined"

**To Reproduce**
Steps to reproduce the behaviour:
I am using vscode coverage with jacoco and I have found a bug parsing a jacoco xml report. I attach the file for further inspection. 
The complete stack trace is:
```
[1556875420792][coverageservice]: Loading 1 file(s)
[1556875420792][coverageservice]: Loaded 1 data file(s)
[1556875420805][coverageparser][jacoco-parse]: Error: filename: /Users/fox/Documents/workspace/2019-04-09-Automation/metrics/build/reports/jacoco.xml Cannot read property 'filter' of undefined
[1556875420805][coverageparser][jacoco-parse]: Stacktrace: TypeError: filename: /Users/fox/Documents/workspace/2019-04-09-Automation/metrics/build/reports/jacoco.xml Cannot read property 'filter' of undefined
	at getCounter (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:9:27)
	at /Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:33:27
	at Array.map (<anonymous>)
	at /Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:23:35
	at Array.forEach (<anonymous>)
	at unpackage (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:21:14)
	at /Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:123:22
	at Parser.<anonymous> (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:303:18)
	at Parser.emit (events.js:182:13)
	at SAXParser.onclosetag (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:261:26)
	at emit (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:624:35)
	at emitNode (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:629:5)
	at closeTag (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:889:7)
	at SAXParser.write (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/sax/lib/sax.js:1436:13)
	at Parser.exports.Parser.Parser.parseString (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:322:31)
	at Parser.bind [as parseString] (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:5:59)
	at exports.parseString (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/xml2js/lib/parser.js:354:19)
	at Object.parse.parseContent (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/jacoco-parse/source/index.js:116:5)
	at xmlExtractJacoco.Promise (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:103:32)
	at new module.exports.t.exports (/Users/fox/.vscode/extensions/vscjava.vscode-java-dependency-0.4.0/dist/extension.js:1:120859)
	at CoverageParser.xmlExtractJacoco (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:94:16)
	at CoverageParser.<anonymous> (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:42:47)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:7:71)
	at new module.exports.t.exports (/Users/fox/.vscode/extensions/vscjava.vscode-java-dependency-0.4.0/dist/extension.js:1:120859)
	at __awaiter (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:3:12)
	at CoverageParser.filesToSections (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:27:16)
	at CoverageService.<anonymous> (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/coverage-system/coverageservice.js:76:64)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/fox/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/coverage-system/coverageservice.js:4:58)
	at i (/Users/fox/.vscode/extensions/vscjava.vscode-java-dependency-0.4.0/dist/extension.js:1:101710)
	at /Users/fox/.vscode/extensions/vscjava.vscode-java-dependency-0.4.0/dist/extension.js:1:102054
```

**Expected behaviour**
The normal behaviour of the plugin 

**Desktop (please complete the following information):**
 - OS: macos
 - Extension Version 2.3.1
 - VSCode Version 1.33.1

**Additional context**
With other classes I don't have any problem.
[jacoco.xml.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/3141306/jacoco.xml.zip)

Thanks very much for your work!
S.

**Comment by ryanluker** [comment]
@foxpluto Thanks for submitting a bug! I probably wont be able to investigate this one until the `2.4.0` release is finished. One other thing you could maybe do is report this issue to https://github.com/vokal/jacoco-parse and see if they would be able to fix it on their end (if it truly is an issue on their side). Otherwise I should be able to start work on this in the next `2.4.1` release!

**Comment by ryanluker** [comment]
@foxpluto pretty annoying but https://github.com/vokal/jacoco-parse has been deprecated / made read only. We might need to consider writing our own jacoco xml parser (similar to what we will have to do for the python coverage one here https://github.com/ryanluker/vscode-coverage-gutters/issues/224). I will put this into the `3.0.0` release with the python coverage support.

**Comment by foxpluto** [comment]
Hi Ryan,

thanks for the update. This is a sad news.
In the meantime I have locked the Jacoco version to 0.7.9 which works.

Hope to have some news soon.

Regards,
Steafano

**Comment by ryanluker** [comment]
Closing this ticket due to Jacoco being deprecated and archived now.
There is also other options for python devs and soon we will also support coverage in `3.0.0`.
