### ISSUE TITLE
Error Could not find a Coverage file!

### ISSUE THREAD

**Issue by fela93** [ryanluker/vscode-coverage-gutters#273]
**Describe the bug**
Error Could not find a Coverage file!

**To Reproduce**
on settings.json I have exactly path to my lcov file
"coverage-gutters.lcovname": "/home/user/projectx/lcov/lcov_all.info"

**Expected behavior**
lcov should be found and loaded to see coverage

**Screenshots**
[1595917778880][coverageservice]: INITIALIZING
[1595917785204][coverageservice]: LOADING
[1595917806633][gutters]: Error Could not find a Coverage file!
[1595917806633][gutters]: Stacktrace Error: Could not find a Coverage file!
	at FilesLoader.<anonymous> (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.5.1/out/src/files/filesloader.js:32:27)
	at Generator.next (<anonymous>)
	at fulfilled (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.5.1/out/src/files/filesloader.js:4:58)
[1595917806633][coverageservice]: RENDERING
[1595917806633][coverageservice]: READY

**Desktop (please complete the following information):**
 - OS:Linux
-  Language: C/C++
 - Extension Version 2.5.1
 - VSCode Version 1.47.2

**Comment by ryanluker** [comment]
@fela93 thanks for submitting a detailed ticket!
If you know exactly the lcov file you want to use it might be better using the manual option.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L132-L136

If that isn't quite working you can also keep using lcvoname but it is meant to be used with just `lcov_all.info`

**Comment by fela93** [comment]
Thanks a lot Ryan
This trick worked for me "coverage-gutters.manualCoverageFilePaths"
