### ISSUE TITLE
Attempting to parse cobertura.xml fails after converting from visual studio .coverage binary.

### ISSUE THREAD

**Issue by GrahamMThomas** [ryanluker/vscode-coverage-gutters#438]
**Describe the bug**
After converting to cobertura xml file from .coverage binary file, the parsing fails within the cobertura parser. I don't see any reason this shouldn't work given this looks like a valid cobertura xml file to me. 

**To Reproduce**
Steps to reproduce the behaviour:
1. dotnet test --config <config file>
  - This config file specifying `<DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Culture=neutral">`
2. Convert .coverage file to cobertura.xml using dotnet coverage tool.
  - `dotnet-coverage merge -f cobertura -o $code_coverage_file_name $latest_file`
  - ![image](https://github.com/ryanluker/vscode-coverage-gutters/assets/14031456/3a163399-569d-434b-8f20-529849c6ec69)
3. __NOTE__ This file can be processed by report generator and work correctly.

**Expected behaviour**
File to be parsed successfully and coverage gutters to appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `Windows via WSL`
 - Extension Version: `v2.11.1`
 - VSCode Version: `1.86.2`

**Additional context**
Stack Trace:

```
[1709159241884][coverageservice]: READY
[1709159243317][coverageservice]: LOADING
[1709159244720][coverageservice]: Loading 1 file(s)
[1709159244720][coverageservice]: <REDACTED>/code_coverage.xml
[1709159244722][coverageservice]: Loaded 1 data file(s)
[1709159245196][coverageparser][cobertura-parse]: Error: filename: <REDACTED>/code_coverage.xml Cannot read properties of undefined (reading '0')
[1709159245196][coverageparser][cobertura-parse]: Stacktrace: TypeError: filename: /home/gthomas/repos/Service.HealthDeidentification/code_coverage.xml Cannot read properties of undefined (reading '0')
    at unpackage (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/cobertura-parse/source/index.js:75:34)
    at /home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/cobertura-parse/source/index.js:137:22
    at Parser.<anonymous> (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (node:events:514:28)
    at SAXParser.onclosetag (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/xml2js/lib/parser.js:354:19)
    at parse.parseContent (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/cobertura-parse/source/index.js:130:5)
    at /home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/out/src/files/coverageparser.js:72:52
    at new Promise (<anonymous>)
    at CoverageParser.xmlExtractCobertura (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/out/src/files/coverageparser.js:63:16)
    at CoverageParser.<anonymous> (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/out/src/files/coverageparser.js:36:47)
    at Generator.next (<anonymous>)
    at /home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/tslib/tslib.js:114:16)
    at CoverageParser.filesToSections (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/out/src/files/coverageparser.js:19:38)
    at CoverageService.<anonymous> (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/out/src/coverage-system/coverageservice.js:84:60)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gthomas/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.11.1/node_modules/tslib/tslib.js:115:62)
```

**Comment by GrahamMThomas** [comment]
I've found a workaround after viewing some of the sample files in https://github.com/fschwaiger/cobertura-parse.

Looks like the dotnet-compile doesn't include this:
![image](https://github.com/ryanluker/vscode-coverage-gutters/assets/14031456/547146a4-e8b6-4800-aa25-6193f847a957)

<source> tag. Once I added that, even with dummy values, everything was working.

**Comment by ryanluker** [comment]
> I've found a workaround after viewing some of the sample files in https://github.com/fschwaiger/cobertura-parse.
> 
> Looks like the dotnet-compile doesn't include this: ![image](https://private-user-images.githubusercontent.com/14031456/308750671-547146a4-e8b6-4800-aa25-6193f847a957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODk4NDYsIm5iZiI6MTcxMDA4OTU0NiwicGF0aCI6Ii8xNDAzMTQ1Ni8zMDg3NTA2NzEtNTQ3MTQ2YTQtZThiNi00ODAwLWFhMjUtNjE5M2Y4NDdhOTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE2NTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjRiZTM1MTEyMzBmNTYyZTYxOTkyOGIxMDIzMjg1MGI4Yzc1ZTEyMDA1ZjU0NDdiN2ViMWM5NWU4MmE2YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4XGh3Eb4YYLHaLOPT43qUCGKke1KLGk2DgdDE4Dcoe8)
> 
> `<sources>` tag. Once I added that, even with dummy values, everything was working.
> 
> To codify the workaround:
> 
> ```shell
> dotnet-coverage merge -f cobertura -o $code_coverage_file_name $latest_file
> sed -i '/<coverage/a <sources><source /></sources>' $code_coverage_file_name
> ```
> 
> This may be more of an issue for the `cobertura-parse` library. Let me know if I should punt this to over there instead.

Thanks for submitting an issue and figuring out a workaround!
Yes, this definitely would be more of an upstream project issue.

**Comment by ryanluker** [comment]
> [@ryanluker](https://github.com/ryanluker) Same issue here, resolved the same way. I was using ReportGenerator to convert coverlets opencover reports to Coberrtura as required by coverage-gutters. Turns out that it won't read ReportGenerators files unless you add the node. Another workaround is just to have coverlet generate Cobertura format as well but that means running the tests twice.

Gotcha thanks for providing more workarounds! We can probably collect all these into some documentation within the QUICKSTART.md file 🤔.

**Comment by ryanluker** [comment]
Closing due to being an upstream issue, but there are good workarounds in the issue (thank you contributors!)
